// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favorites.sql

package db

import (
	"context"
	"database/sql"
)

const addFavorite = `-- name: AddFavorite :one
INSERT INTO favorites (user_id, recipe_id)
VALUES ($1, $2)
RETURNING id, user_id, recipe_id, created_at
`

type AddFavoriteParams struct {
	UserID   sql.NullInt32 `json:"user_id"`
	RecipeID sql.NullInt32 `json:"recipe_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) (Favorite, error) {
	row := q.db.QueryRowContext(ctx, addFavorite, arg.UserID, arg.RecipeID)
	var i Favorite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipeID,
		&i.CreatedAt,
	)
	return i, err
}

const isFavorite = `-- name: IsFavorite :one
SELECT EXISTS(
  SELECT 1 FROM favorites
  WHERE user_id = $1 AND recipe_id = $2
) as is_favorite
`

type IsFavoriteParams struct {
	UserID   sql.NullInt32 `json:"user_id"`
	RecipeID sql.NullInt32 `json:"recipe_id"`
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFavorite, arg.UserID, arg.RecipeID)
	var is_favorite bool
	err := row.Scan(&is_favorite)
	return is_favorite, err
}

const listFavoritesByUser = `-- name: ListFavoritesByUser :many
SELECT f.id as favorite_id, f.user_id, f.recipe_id, f.created_at, 
  r.title, r.description, r.cuisine, r.difficulty, r.diet_type, 
  r.prep_time_minutes, r.cook_time_minutes, r.total_time_minutes, r.servings,
  COALESCE((SELECT ROUND(AVG(rating)::numeric, 1) FROM ratings WHERE recipe_id = r.id)::text, '0') as average_rating
FROM favorites f
JOIN recipes r ON r.id = f.recipe_id
WHERE f.user_id = $1
ORDER BY f.created_at DESC
`

type ListFavoritesByUserRow struct {
	FavoriteID       int32          `json:"favorite_id"`
	UserID           sql.NullInt32  `json:"user_id"`
	RecipeID         sql.NullInt32  `json:"recipe_id"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Cuisine          sql.NullString `json:"cuisine"`
	Difficulty       sql.NullString `json:"difficulty"`
	DietType         sql.NullString `json:"diet_type"`
	PrepTimeMinutes  sql.NullInt32  `json:"prep_time_minutes"`
	CookTimeMinutes  sql.NullInt32  `json:"cook_time_minutes"`
	TotalTimeMinutes sql.NullInt32  `json:"total_time_minutes"`
	Servings         sql.NullInt32  `json:"servings"`
	AverageRating    interface{}    `json:"average_rating"`
}

func (q *Queries) ListFavoritesByUser(ctx context.Context, userID sql.NullInt32) ([]ListFavoritesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listFavoritesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritesByUserRow
	for rows.Next() {
		var i ListFavoritesByUserRow
		if err := rows.Scan(
			&i.FavoriteID,
			&i.UserID,
			&i.RecipeID,
			&i.CreatedAt,
			&i.Title,
			&i.Description,
			&i.Cuisine,
			&i.Difficulty,
			&i.DietType,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.TotalTimeMinutes,
			&i.Servings,
			&i.AverageRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites WHERE user_id = $1 AND recipe_id = $2
`

type RemoveFavoriteParams struct {
	UserID   sql.NullInt32 `json:"user_id"`
	RecipeID sql.NullInt32 `json:"recipe_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removeFavorite, arg.UserID, arg.RecipeID)
	return err
}
