// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Favorite struct {
	ID        int32
	UserID    sql.NullInt32
	RecipeID  sql.NullInt32
	CreatedAt sql.NullTime
}

type Rating struct {
	ID        int32
	UserID    sql.NullInt32
	RecipeID  sql.NullInt32
	Rating    sql.NullInt32
	CreatedAt sql.NullTime
}

type Recipe struct {
	ID              int32
	Title           string
	Cuisine         sql.NullString
	Difficulty      sql.NullString
	CookTimeMinutes sql.NullInt32
	Servings        sql.NullInt32
	Tags            []string
	Ingredients     pqtype.NullRawMessage
	Steps           pqtype.NullRawMessage
	Nutrition       pqtype.NullRawMessage
	CreatedAt       sql.NullTime
}

type User struct {
	ID           int32
	Username     sql.NullString
	CreatedAt    sql.NullTime
	Email        sql.NullString
	PasswordHash sql.NullString
}
